<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountsTableSeeder extends Seeder
{
    public function run()
    {

        DB::table('accounts')->delete();
        
        DB::table('accounts')->insert([


            [
                'id' => 1,
                'account_name' => 'الاصول',
                'phone' => null,
                'parent_id' => null, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id' => 2,
                'account_name' => 'الاصول المتداولة',
                'phone' => null,
                'parent_id' => 1, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'account_name' => 'الاصول غير المتداولة',
                'phone' => null,
                'parent_id' => 1, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'account_name' => 'الاصول غير الملموسة',
                'phone' => null,
                'parent_id' => 1, 
                'can_delete' => 0,
                'start_amount' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'account_name' => 'الاراضى',
                'phone' => null,
                'start_amount' => 0,

                'parent_id' => 2, 
                'can_delete' => 0,
                'type'=>'7',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'account_name' => 'المبانى',
                'phone' => null,
                'parent_id' => 2, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'7',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 7,
                'account_name' => 'الالات و المعدات',
                'phone' => null,
                'parent_id' => 2, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'7',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'account_name' => 'السيارات',
                'phone' => null,
                'parent_id' => 2, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'7',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'account_name' => 'الاثتسمارات',
                'phone' => null,
                'parent_id' => 2, 
                'start_amount' => 0,
                'can_delete' => 0,
                'type'=>'7',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
      

            [
                'id' => 10,
                'account_name' => 'الخزينه',
                'phone' => null,
                'parent_id' => 3, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 11,
                'account_name' => 'حسابات البنوك',
                'phone' => null,
                'parent_id' => 3, 
                'start_amount' => 0,
                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 12,
                'account_name' => 'العملاء',
                'phone' => null,
                'parent_id' => 3, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'account_name' => 'المخزون',
                'phone' => null,
                'parent_id' => 3, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'account_name' => 'مصروف مقدم',
                'phone' => null,
                'parent_id' => 3, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'account_name' => 'ايراد مستحق',
                'phone' => null,
                'parent_id' => 3, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],


    

            [
                'id' => 16,
                'account_name' => 'الشهرة',
                'phone' => null,
                'parent_id' => 4, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'account_name' => 'برائة الاختراع',
                'phone' => null,
                'parent_id' => 4, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'account_name' => 'مصاريف التأثيث',
                'phone' => null,
                'parent_id' => 4, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'account_name' => 'الالتزامات',
                'phone' => null,
                'parent_id' => null, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 20,
                'account_name' => 'الخصوم',
                'phone' => null,
                'parent_id' => 19, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 21,
                'account_name' => 'حقوق الملكية',
                'phone' => null,
                'parent_id' => 19, 
                'can_delete' => 0,
                'type'=>'main',
                'start_amount' => 0,

                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'account_name' => 'الموردين',
                'phone' => null,
                'parent_id' => 20, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'account_name' => 'مصروف مستحق',
                'phone' => null,
                'parent_id' => 20, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'account_name' => 'ايراد مقدم',
                'phone' => null,
                'parent_id' => 20, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'account_name' => 'مجمع الاستهلاك',
                'phone' => null,
                'parent_id' => 20, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'account_name' => 'قروض',
                'phone' => null,
                'parent_id' => 20, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],





            [
                'id' => 27,
                'account_name' => 'رأس المال',
                'phone' => null,
                'parent_id' => 21, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 28,
                'account_name' => 'ارباح مرحله',
                'phone' => null,
                'parent_id' => 21, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'account_name' => 'احتياطات',
                'phone' => null,
                'parent_id' => 21, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 30,
                'account_name' => 'جارى المالك',
                'phone' => null,
                'parent_id' => 21, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'id' => 31,
                'account_name' => 'المصروفات و الخسائر',
                'phone' => null,
                'parent_id' => null, 
                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'start_amount' => 0,

                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'account_name' => 'مصروفات نقدية',
                'phone' => null,
                'parent_id' => 31, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'account_name' => 'مصروفات غير نقدية',
                'phone' => null,
                'parent_id' => 31, 
                'can_delete' => 0,
                'type'=>'main',
                'start_amount' => 0,

                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'account_name' => 'الرواتب ',
                'phone' => null,
                'parent_id' => 32, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'20',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'account_name' => 'المشتريات ',
                'phone' => null,
                'parent_id' => 32, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'19',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'account_name' => 'مصاريف المشتريات ',
                'phone' => null,
                'parent_id' => 32, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'19',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'account_name' => 'الايجارات ',
                'phone' => null,
                'parent_id' => 32, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'23',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'account_name' => 'مصاريف الكهرباء و المياة ',
                'phone' => null,
                'parent_id' => 32, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'23',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'account_name' => 'مصروف النت ',
                'phone' => null,
                'parent_id' => 32, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'23',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'account_name' => 'مصاريف تسويقية ',
                'phone' => null,
                'parent_id' => 32, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'21',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'account_name' => 'مصاريف نثريات ',
                'phone' => null,
                'parent_id' => 32, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'23',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
         

            [
                'id' => 40,
                'account_name' => 'مصروف الاهلاك ',
                'phone' => null,
                'parent_id' => 33, 
                'can_delete' => 0,
                'type'=>'main',
                'start_amount' => 0,

                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'account_name' => 'الاطفاء',
                'phone' => null,
                'parent_id' => 33, 
                'can_delete' => 0,
                'type'=>'main',
                'start_amount' => 0,

                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'account_name' => 'مصاريف اخرى',
                'phone' => null,
                'parent_id' => 33, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // [
            //     'id' => 43,
            //     'account_name' => 'مصاريف اخرى',
            //     'phone' => null,
            //     'parent_id' => 33, 
            //     'can_delete' => 0,
            //     'start_amount' => 0,

            //     'type'=>'main',
            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'id' => 44,
                'account_name' => 'الايرادات',
                'phone' => null,
                'parent_id' => null, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'account_name' => 'نقدية',
                'phone' => null,
                'parent_id' => 44, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
   



            [
                'id' => 46,
                'account_name' => 'غير نقدية',
                'phone' => null,
                'parent_id' => 44, 
                'can_delete' => 0,
                'start_amount' => 0,

                'type'=>'main',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'account_name' => 'المبيعات',
                'phone' => null,
                'parent_id' => 45, 
                'start_amount' => 0,

                'can_delete' => 0,
                'type'=>'18',
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        
        [
            'id' => 48,
            'account_name' => 'الخدمات',
            'phone' => null,
            'parent_id' => 45, 
            'can_delete' => 0,
            'type'=> 'none',
            'start_amount' => 0,

            'current_balance' => 0.00,
            'net_debit' => 0.00,
            'net_credit' => 0.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
    
    [
        'id' => 49,
        'account_name' => 'ايرادات اخرى',
        'phone' => null,
        'parent_id' => 45, 
        'can_delete' => 0,
        'type'=>'main',
        'current_balance' => 0.00,
        'net_debit' => 0.00,
        'start_amount' => 0,

        'net_credit' => 0.00,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'id' => 50,
        'account_name' => 'المستقطعات',
        'phone' => null,
        'parent_id' => 46, 
        'can_delete' => 0,
        'type'=>'main',
        'start_amount' => 0,

        'current_balance' => 0.00,
        'net_debit' => 0.00,
        'net_credit' => 0.00,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 51,
        'account_name' => 'مكاسب اخرى',
        'phone' => null,
        'parent_id' => 46, 
        'can_delete' => 0,
        'start_amount' => 0,

        'type'=> 'none',
        'current_balance' => 0.00,
        'net_debit' => 0.00,
        'net_credit' => 0.00,
        'created_at' => now(),
        'updated_at' => now(),
    ],



            [
                'id' => 52,
                'account_name' => 'حسابات الضرائب',
                'phone' => null,
                'parent_id' => null, 
                'can_delete' => 0,
                'type'=>'main',
                'start_amount' => 0,

                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'account_name' => 'حساب ضريبة الزكاة',
                'phone' => null,
                'parent_id' => 52, 
                'type'=>'none',
                'start_amount' => 0,

                'can_delete' => 0,
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>54,
                'account_name' => 'حساب ضريبة القيمة المضافه',
                'phone' => null,
                'parent_id' => 52, 
                'type'=>'none',
                'start_amount' => 0,

                'can_delete' => 0,
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>57,
                'account_name' => 'حساب البنك العام',
                'phone' => null,
                'parent_id' => 11, 
                'type'=>'none',
                'start_amount' => 0,

                'can_delete' => 0,
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' =>58,
                'account_name' => 'حساب الخزينة الرئيسية',
                'phone' => null,
                'parent_id' => 10, 
                'type'=>'none',
                'start_amount' => 0,

                'can_delete' => 0,
                'current_balance' => 0.00,
                'net_debit' => 0.00,
                'net_credit' => 0.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'id' => 1,
            //     'account_name' => 'الخزينه',
            //     'phone' => null,
            //     'parent_id' => null, 
            //     'can_delete' => 0,
            //     'type'=>'main',
            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 2,
            //     'account_name' => 'العملاء',
            //     'phone' => null,
            //     'parent_id' => null, 
            //     'can_delete' => 0,
            //     'type'=>'main',

            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 3,
            //     'account_name' => 'الموردين',
            //     'phone' => null,
            //     'parent_id' => null, 
            //     'can_delete' => 0,
            //     'type'=>'main',

            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 4,
            //     'account_name' => 'حسابات البنوك',
            //     'phone' => null,
            //     'parent_id' => null, 
            //     'can_delete' => 0,
            //     'type'=>'main',

            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 5,
            //     'account_name' => 'حساب المصاريف العمومية و الادارية',
            //     'phone' => null,
            //     'parent_id' => null, 
            //     'can_delete' => 0,
            //     'type'=>'main',

            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 6,
            //     'account_name' => 'حساب المصاريف التسويقية',
            //     'phone' => null,
            //     'parent_id' => null, 
            //     'can_delete' => 0,
            //     'type'=>'main',

            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],         
            
            



            // [
            //     'id' => 7,
            //     'account_name' => 'حسابات الضرائب',
            //     'phone' => null,
            //     'parent_id' => null, 
            //     'can_delete' => 0,
            //     'type'=>'main',

            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 8,
            //     'account_name' => 'حساب ضريبة الزكاة',
            //     'phone' => null,
            //     'parent_id' => 7, 
            //     'type'=>'branch',

            //     'can_delete' => 0,
            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 9,
            //     'account_name' => 'حساب ضريبة القيمة المضافه',
            //     'phone' => null,
            //     'parent_id' => 7, 
            //     'type'=>'branch',

            //     'can_delete' => 0,
            //     'current_balance' => 0.00,
            //     'net_debit' => 0.00,
            //     'net_credit' => 0.00,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
        ]);
    }
}
